#!/bin/bash

DOCKER_LOGIN=$(aws ecr get-login | grep -e 'docker login')

DOCKER_PASSWORD=$(echo $DOCKER_LOGIN | grep -o -e '-p .*==' | cut -d ' ' -f2)

DOCKER_REGISTRY=$(echo $DOCKER_LOGIN | grep  -o -e 'https.*')

mkdir -p .docker

cat << EOF > .docker/config.json
{
	"auths": {
		"$DOCKER_REGISTRY": {
			"auth": "$DOCKER_PASSWORD"
		}
	}
}
EOF

chmod 600 .docker/config.json

rm docker.tar.gz -f

tar czf docker.tar.gz .docker
